### ISSUE TITLE
Add search function

### ISSUE THREAD

**Issue by K4stor** [Whiffer/SwiftUI-Core-Data-Test#2]
Hi there I am trying to use SwiftUI with CoreData, and you code helps alot, thanks !

But now I am trying to add search functionality. And I am stuck at the place
where my searchBar has new text and must somehow promote that change into the CoreDataSource, to that the fetchResult is updated. 

If you could add search it would be a huge help to me and others !

**Comment by Whiffer** [comment]
Hi. This is good timing. I started working on a search view just yesterday. I will add it to my sample project when I finish it in the next day or two.

**Comment by Whiffer** [comment]
Here it is:

Tab 5: Demonstrates how to use a SearchBar with the CoreDataDataSource
Added a new method to load the data source using an NSPredicate to supply data to a ForEach List.
Created a UIViewRepresentable SearchBar that accepts the search text and returns a new
NSPredicate back to the SwiftUI view after each keystroke.

There might be other ways to do this but this seemed to be the most straight forward at the time.

**Comment by K4stor** [comment]
OMG Thank you so much ! Will check it out tonight. Once I understood that kind of data flow it will be able to do so much more.

**Comment by K4stor** [comment]
Just one thought.... Maybe it would be nicer to hand over the search term to the coreDataSource, instead of the predicate. The DataSource would then build the predicate. To me it just seems cleaner if the actual view didn't build core data objects. What do you think ?

**Comment by Whiffer** [comment]
Yes, I also try to keep Core Data out of my Views and ViewControllers.  However, in this case, NSPredicate is a Foundation class, not Core Data, so I don't really have a problem with it. 

Also, in the case of my own App, my SearchBar uses a ScopeBar (e.g. "Starts With", "Contains", "Exact Match", etc.) to give the search text a different context and therefore influence the creation of the  predicate.  In my case, if the predicate was created by the data source, I would have to put View specific code into my general purpose data source.

**Comment by K4stor** [comment]
Ah I see, good point
